### ISSUE TITLE
"AttributeError: Can't pickle local object" when checking IP with '-ip' flag

### ISSUE THREAD

**Issue by iamGBOX** [t-a-y-l-o-r/checkip#31]
**Describe the bug**
When attempting to run a check on an IP address, I get the following AttributeError with traceback:

```
Traceback (most recent call last):
  File "src/checkip.py", line 344, in <module>
    IP_Checker().main()
  File "src/checkip.py", line 136, in main
    self.run_collector_pipeline(actual_ips.keys())
  File "src/checkip.py", line 208, in run_collector_pipeline
    process.start()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 283, in _Popen
    return Popen(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'ArgumentParser.__init__.<locals>.identity'
```

As a note, I'm not seeing this error on a machine running Ubuntu.

**To Reproduce**
1. Run checkip with '-ip' flag
2. See error message

**Screenshots**

<img width="987" alt="Screen Shot 2021-06-10 at 9 42 29 AM" src="https://user-images.githubusercontent.com/47159600/121564320-2e2cca80-c9d0-11eb-926f-7bc8c81d8323.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 11.4

**Python Version**
Python 3.8.0

**Branch Used**
Main

**Comment by t-a-y-l-o-r** [comment]
This is a problem with Python 3.8. In 3.8 the default mode for multiprocessing in MacOS is to `spawn` instead of `fork`. This requires all objects to be picklable

**Comment by t-a-y-l-o-r** [comment]
For now I would recommend using python 3.7.x or alternatively I have setup a hotfix that should work: https://github.com/t-a-y-l-o-r/checkip/tree/multiprocessing_fix_macos

**Comment by t-a-y-l-o-r** [comment]
after some in-depth research it looks like the use of fork as the multiprocess default is inconsistent at best, and can corrupt memory in hidden ways, at worst.

The `fix` here would be migrating everything to `spawn` which is the default in macos and windows anyway. 
Two main considerations here: 1) `spawn` is significantly slower than `fork`   and 2) it requires everything be `pickle`d per the error above

Ultimately it would not be desirable to slow down the program since the entire point of using `multiprocess` was to speed up the network call bottleneck. 

There will need to be some profiling to see if the changes are workable and don't impact the user experience too much

**Comment by t-a-y-l-o-r** [comment]
it might be worth exploring [Pool](https://docs.python.org/3.8/library/multiprocessing.html#multiprocessing.pool.Pool)

**Comment by t-a-y-l-o-r** [comment]
looks like the memory overhead of spawn isn't really that bad in comparison to fork for cPython. Since all objects are `written` to for any operation, forcing the `copy-on-write` to execute for the fork. (this even occurs for something as basic as iterating over a list of objects)

**Comment by t-a-y-l-o-r** [comment]
after some testing it looks like `spawn` is an order of magnitude slower than `fork` on instant, and linear operations.
Would imagine this would apply to basic network calls as well

**Comment by t-a-y-l-o-r** [comment]
[ray](https://pypi.org/project/ray/) is claiming to be orders of magnitude faster than the built-in `multiprocessing` package. 

This would constitute a significant re-write of the core data processing pipeline within the application. This will be both tricky and time consuming to get right

**Comment by t-a-y-l-o-r** [comment]
ray seems to be scaling incredibly well on both instant and linear operations. It often beats even fork, especially as the data size scales up

**Comment by t-a-y-l-o-r** [comment]
after building out a simple mock of the old modules in ray it looks like there is currently a race-condition issue they are having.
This seems to affect even simple network calls, in particular when using a class as a wrapper for bundling your remote functions
[issue](https://github.com/ray-project/ray/issues/8003)

**Comment by t-a-y-l-o-r** [comment]
after building out a simple mock of the old modules in ray it looks like there is currently a race-condition issue they are having.
This seems to affect even simple network calls, in particular when using a class as a wrapper for bundling your remote functions
[issue](https://github.com/ray-project/ray/issues/8003)

**Comment by t-a-y-l-o-r** [comment]
https://docs.aiohttp.org/en/stable/index.html using asynchronous concurrent calls might be a more light-weight method of refactoring this. Would only require swapping out some core functions and would help streamline a lot of the boilerplate  

in particular `tasks` and `gather` seem rather fancy: https://docs.python.org/3/library/asyncio-task.html

**Comment by t-a-y-l-o-r** [comment]
@iamGBOX try out: `https://github.com/t-a-y-l-o-r/checkip/tree/dev-bugfix-async`
There's a new file you should run: `./src/async_ip.py`

**Comment by t-a-y-l-o-r** [comment]
@iamGBOX checkout [dev](https://github.com/t-a-y-l-o-r/checkip/tree/dev) when you can. it has the new async setup. the output is still weird. But I'll be fixing that in a separate branch

**Comment by iamGBOX** [comment]
Apologies for the delay! I worked with a colleague and was able to get it running after rolling back to Python 3.8.0, reinstalling CLANG, and the Xcode tool chain, and manually installing `multidict` and `aiohttp`
