### ISSUE TITLE
SSL Failed Certificate Verification

### ISSUE THREAD

**Issue by erbesner** [t-a-y-l-o-r/checkip#48]
**Describe the bug**
when executing checkip.py -ip [X.X.X.X] it returns an error.

**To Reproduce**
1.  execute program with `-ip` option and ip address as argument 
2. See error: 
> SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')

**Screenshots**
![Screen Shot 2021-12-16 at 9 50 07 AM](https://user-images.githubusercontent.com/96257357/146423220-7e9a83c7-8e4b-453a-97f8-792b3df98ada.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 12.0.1

**Python Version**
3.10.1

**Branch Used**
main

**Comment by t-a-y-l-o-r** [comment]
@erbesner Thanks for the report

Couple thoughts on what might be causing this. 

Could be macOS itself. Does have certification issues from time to time. Or, it could be the python version here.

Can you try using python 3.9? in the meantime I'll  do some research on any recent macOS changes

**Comment by t-a-y-l-o-r** [comment]
[could be related to](https://stackoverflow.com/questions/42098126/mac-osx-python-ssl-sslerror-ssl-certificate-verify-failed-certificate-verify)

**Comment by erbesner** [comment]
The InstallCertificates.command they provided wasn't working due to user perms I think. I was able to install the certificate(s) it was expecting using `pip3 install --upgrade certifi`, but for some reason it's still returning the same error when I run checkip

**Comment by t-a-y-l-o-r** [comment]
Thanks for waiting, holidays and all that.

-- --


After some testing on mac, it looks like we actually have a have a couple things going on here.

Our list of dependencies only officially supports python 3.8

So you'll want to run this process:

```sh
$ cd ~/foo/bar/checkip
$ git checkout hot-fix-dependencies
$ pipenv install # go get some coffee
$ pipenv shell
$ ./test.sh
```

This should:
- install python 3.8 (our supported version)
- ensure you have all dependencies installed on the 3.8 venv
- check for any errors in the system

Let me know if you have issues with this, or if it works out

**Comment by t-a-y-l-o-r** [comment]
@erbesner just wanted to check in here. Have you had a chance to try out the above?

**Comment by erbesner** [comment]
I haven't had a chance to downgrade to 3.8 yet, I'll get to that sometime this week hopefully

**Comment by erbesner** [comment]
I now have 3.8 installed, and still get the same error when running the program

**Comment by t-a-y-l-o-r** [comment]
at this point it might be worth reinstalling your xcode tool chain or any ssl related dependencies. I'm not able to reproduce this issue on a fresh mac, which would suggest there's something deeper in your setup that is misbehaving
